name: "Release"

on:
  push:
    branches:
      - beta
      - main

jobs:
  release:
    name: "Release"
    permissions:
      contents: write # to be able to publish a github release
      issues: write # to be able to comment on released issues
      pull-requests: write # to be able to comment on released pull requests
    runs-on: ubuntu-latest
    steps:
      - name: "🛎 Checkout"
        uses: actions/checkout@v4
      - name: "📦 Install yq"
        uses: ./.github/actions/install-yq
      - name: "📝 Create .npmrc"
        run: |
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_PUBLISH_PACKAGES_ACCESS_TOKEN }}" >> .npmrc
          echo "@kibisis:registry=https://registry.npmjs.org" >> .npmrc
          echo "access=public" >> .npmrc
      - name: "🧶 Setup Yarn Dependencies"
        uses: ./.github/actions/use-yarn-dependencies
      - name: "📝 Create .env file"
        uses: ./.github/actions/create-env-file
        with:
          provider_id: ${{ vars.PROVIDER_ID }}
          reown_project_id: ${{ vars.REOWN_PROJECT_ID }}
      - name: "🏗️ Build"
        run: yarn build
      - name: "🔖 Release"
        env:
          # appears on the release commits
          GIT_AUTHOR_NAME: kibi-bot
          GIT_AUTHOR_EMAIL: builders@kibis.is
          GIT_COMMITTER_NAME: kibi-bot
          GIT_COMMITTER_EMAIL: builders@kibis.is
          # used to push the release commit and create the tags
          GITHUB_TOKEN: ${{ secrets.READ_AND_WRITE_REPOS_TOKEN }}
        run: yarn semantic-release
